version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: store
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    restart: on-failure

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: on-failure

