version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - 3000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/frontend_build:/usr/share/nginx/html/frontend
      - ./server/images:/usr/share/nginx/html/images
    depends_on:
      - frontend
      - server
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./nginx/frontend_build:/app/dist
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        DB_URL: mysql://root:admin@db:3306/store
    command: npm run setup:start
    environment:
      DB_URL: mysql://root:admin@db:3306/store
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
    volumes:
      - ./server/images:/app/images
    depends_on:
      - db
    restart: on-failure

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: store
    volumes:
      - ./mysql:/var/lib/mysql
    restart: on-failure

