version: '3.8'
services:
  nginx:
    image: nginx:latest
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80
    depends_on:
      - frontend
      - admin
      - server
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.compose
    volumes:
      - client:/app/dist

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile.compose
    volumes:
      - admin:/app/dist

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        DB_URL: mysql://root:admin@db:3306/store
        REDIS_HOST: redis
    command: npm run setup:start
    environment:
      DB_URL: mysql://root:admin@db:3306/store
      REDIS_HOST: redis
    volumes:
      - ./server/images:/app/images
      - client:/app/client
      - admin:/app/admin
    depends_on:
      - db
      - redis
    restart: on-failure


  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: store
    volumes:
      - ./mysql:/var/lib/mysql
    restart: on-failure
  
  redis:
    image: redis:latest
    environment:
      REDIS_PASSWORD: admin
    restart: on-failure

volumes:
  client:
  admin:


