version: '3.8'
services:
  nginx:
    image: nginx:latest
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
       - ./server/images:/usr/share/nginx/html/images
    ports:
      - 3000:80
    restart: on-failure

  app:
    image: ghcr.io/tommys725/ierg4210-shop:latest
    command: npm run start
    environment:
      DB_URL: mysql://root:admin@db:3306/store
      REDIS_HOST: redis
      REQ_SSL: 'false'
    volumes:
      - ./server/images:/app/images
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/healthz || exit 1
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: on-failure


  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: store
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3
    restart: on-failure
  
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 3
    restart: on-failure



