/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as withListImport } from './routes/__withList'
import { Route as IndexImport } from './routes/index'
import { Route as withListProductsPidImport } from './routes/__withList/products.$pid'

// Create/Update Routes

const withListRoute = withListImport.update({
  id: '/__withList',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const withListProductsPidRoute = withListProductsPidImport.update({
  path: '/products/$pid',
  getParentRoute: () => withListRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/__withList': {
      preLoaderRoute: typeof withListImport
      parentRoute: typeof rootRoute
    }
    '/__withList/products/$pid': {
      preLoaderRoute: typeof withListProductsPidImport
      parentRoute: typeof withListImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  withListRoute.addChildren([withListProductsPidRoute]),
])

/* prettier-ignore-end */
