name: Deploy

concurrency: production

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
  packages: write

jobs:
    deploy:

        runs-on: ubuntu-latest

        steps:
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Set short git commit SHA
              id: vars
              run: |
                calculatedSha=$(git rev-parse --short ${{ github.sha }})
                echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
        
            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                registry: https://ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: ghcr/TommyS725/shop-demo:${{github.env.COMMIT_SHORT_SHA}}
                build-args: |
                  PAYPAL_CLIENT_ID=${{ secrets.PAYPAL_CLIENT_ID }}